version: '3.5'

services:
  lumen:
    container_name: ciu_bradev
    ports:
      - "8001:8001"
    volumes:
      - .:/var/www/html
      - ./vendor:/var/www/html/vendor/
    build: .
    command: php -S lumen:8001 -t public
    restart: always

  db:
    container_name: mysql
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: ciu_bradev

  nginx:
    image: nginx:1.17-alpine
    container_name: travellist-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d